# Netlify CMS Folder Collection. See https://www.netlifycms.org/docs/collection-types#folder-collections
name: code_fields
identifier_field: name
collection_type: folder
label: Code Fields
label_singular: Code Field
description: "The code widget provides a code editor (powered by Codemirror) with optional syntax awareness. Can output the raw code value or an object with the selected language and the raw code value."
folder: "data/netlifycms/fields"
fields:
  - import: field nc-field-name
    field_type: import
  - import: field nc-field-label
    field_type: import
  - import: field nc-field-required
    field_type: import
  - import: field nc-field-widget
    field_type: import
    extend:
      default: code
  - import: field nc-field-field_type
    field_type: import
    extend:
      default: code
  - label: default
    name: default
    field_type: code
    output_code_only: true
    default_language: YAML
    widget: code
    required: false
  - import: field nc-field-hint
    field_type: import
  - import: field nc-field-default_language
    field_type: import
  - import: field nc-field-allow_language_selection
    field_type: import
  - import: field nc-field-keys
    field_type: import
  - import: field nc-field-output_code_only
    field_type: import
filter: {field: field_type, value: code}
create: true
publish: false
hide: false
delete: true
format: yml
extension: yml
summary: "{{filename}}"
editor:
  preview: true
