label: Display Fields
name: display_fields
widget: list
field_type: list
component: field
required: false
hint: List one or more names of fields in the referenced collection that will render in the autocomplete menu of the control. Defaults to value_field. Syntax to reference nested fields is similar to that of value_field.