label: Buttons
name: buttons
widget: select
field_type: select
component: field
options:
  - bold
  - italic
  - code
  - link
  - heading-one
  - heading-two
  - heading-three
  - heading-four
  - heading-five
  - heading-six
  - quote
  - bulleted-list
  - numbered-list
multiple: true
default:
  - bold
  - italic
  - code
  - link
  - heading-one
  - heading-two
  - heading-three
  - heading-four
  - heading-five
  - heading-six
  - quote
  - bulleted-list
  - numbered-list
hint: The formatting buttons to display (all shown by default).
