label: Media Library
name: media_library
widget: object
field_type: object
component: config
hint: Select from Cloudinary or Uploadcare, and configure connection to your account.
required: false
collapsed: true
fields:
  - import: field nc-field-name
    extend: 
      widget: select
      field_type: select
      options: [cloudinary, uploadcare]
      required: false
  - label: Config
    name: config
    widget: string
    field_type: string
    hint: a configuration object that will be passed directly to the media library being used - available options are determined by the library
    required: false