label: Netlify CMS
name: tnd_netlifycms
widget: object
field_type: object
component: config
required: false
collapsed: true
hint: Settings associated with hugo-module-tnd-netlifycms.
fields:
  - label: CMS Version
    name: cms_version
    widget: string
    field_type: string
    required: false
    hint: Semantic versioning string to be used when calling CDN endpoint. Defaults to ^2.0.0. See https://github.com/netlify/netlify-cms/releases for current releases. 
